# Generated by Django 3.1.1 on 2020-09-17 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
